# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov-console/all/simplecov-console.rbi
#
# simplecov-console-0.4.2
class SimpleCov::Formatter::Console
  def colorize(s); end
  def format(result); end
  def missed(missed_lines); end
  def pct(obj); end
  def self.table_options; end
  def self.table_options=(arg0); end
end
